### PR TITLE
Remove dead assignments and unused local variables.

### LINKED ISSUE #46: Clang Static Analysis reports logic error
"
status_t TGenericDirentParser::AddEntries(const char *strDirList, const char *option)
30	{
31		status_t status = B_OK;
32		uint32 st = 1;
33		BList list;
34		BString strdir(strDirList), curdir;
35		strdir.ReplaceAll("\r\n", "\n");
36		strdir.ReplaceAll("\r", "\n");
39		char *p = (char *)strdir.String();
40		while (*p != 0) {
1
Loop condition is false. Execution continues on line 49	
→
49		for(int32 i = 0; i < list.CountItems(); i++) {
2
←
Assuming the condition is true	
→
3
←
Loop condition is true.  Entering loop body	
→
7
←
Assuming the condition is true	
→
8
←
Loop condition is true.  Entering loop body	
→
50			p = (char *)list.ItemAt(i);
53			if (strlen(p) == 0) {
4
←
Assuming the condition is true	
→
5
←
Taking true branch	
→
9
←
Assuming the condition is false	
→
10
←
Taking false branch	
→
54				st = 0;
55				continue;
6
←
 Execution continues on line 49	
→
57			if (st == 0) {
11
←
Taking true branch	
→
58				st = 1;
59				if (strcmp(option, "R") == 0) {
12
←
Taking true branch	
→
60					curdir.SetTo(p);
61					if (curdir.String()[curdir.Length() - 1] == ':') curdir.ReplaceLast(":", "");
13
←
The left operand of '==' is a garbage value due to array index out of bounds
"

### PR DESCRIPTION
**Pull request by emily0618**
Fixes #46

### CODE REVIEW

**Comment by emily0618** [comment]
I don't know how the array [index](https://github.com/HaikuArchives/FtpPositive/blob/master/src/DirentParser.cpp#L61) can be out of bound?
`if (curdir.String()[curdir.Length() - 1] == ':') curdir.ReplaceLast(":", "");`

**Comment by scottmc** [comment]
if curdir.length() results in a zero, and then you substract 1 you have an index of -1 which is invalid  Perhaps check if curdir.length() is > 0 first?  I haven't looked at surrounding code yup, but that'd be my guess here.

**Comment by emily0618** [comment]
I thought of that, but this [block](https://github.com/HaikuArchives/FtpPositive/blob/master/src/DirentParser.cpp#L53) makes it impossible for `p` to be empty when we get to this [line](https://github.com/HaikuArchives/FtpPositive/blob/master/src/DirentParser.cpp#L60):
`curdir.SetTo(p);`
so `curdir.Length()` must be positive?

**Comment by owenca** [comment]
@emily0618 It's probably a false positive. Replace curdir.length() with strlen(p) and see what happens. Also, that line is quite messy. See if you can help clean it up.

**Comment by emily0618** [comment]
> Replace curdir.length() with strlen(p) and see what happens.

It fixed the error :)

> Also, that line is quite messy. See if you can help clean it up.

Done!

**Comment by owenca** [comment]
Neat!

**Comment by humdingerb** [comment]
Thanks!

**Pull request merged**
