### PR TITLE
Should fix the 2GB problem

### PR DESCRIPTION
**Pull request by janus2**
THIS IS NOT TESTED.
@humdingerb could you verify if this fixes the 2GB problem issue #18. Thanks

### CODE REVIEW

**Comment by ohnx** [comment]
Hmm, what makes this issue interesting is that the old type used to be `uint32`, which should have a max value of 4GiB and not 2. I haven't tested this either, though, so maybe this works :)

**Comment by humdingerb** [comment]
I'm afraid it didn't change a thing. Sorry.

**Comment by janus2** [comment]
I'll try to investigate better now that I found this ftp://speedtest.tele2.net/

**Comment by janus2** [comment]
What a bug it was converted from string to int32, then a different number of times from int64 to int32
eureka

**Comment by janus2** [comment]
We must change the screenshot, it's not good sign when the screenshot of your application contains a few bugs

**Comment by humdingerb** [comment]
Confirmed to work! Thanks!
Think you can avoid showin 4KB for all the directories? :)

**Comment by janus2** [comment]
With the standard Column 0 bytes is all we can do... I must check the code but at the moment I am a little busy. I let you know what can we do.

**Comment by scottmc** [comment]
Merging work done so far as it's been confirmed to fix reported issue.

**Pull request merged**
